### PR TITLE
New vibration pattern on BT disconnect

### PR DESCRIPTION
**Pull request by pjexposito**
I've change a normal pulse for a vibe pattern.

### CODE REVIEW

**Comment by tilden** [comment]
Interesting, what do you like better about this vibration pattern?

**Comment by pjexposito** [comment]
With the usual vibe, I can mistake the bt lost with a notification. With a
different pattern, I can identify when I lost the conection without look at
the screen.

Greets,

Pedro

**Comment by tilden** [comment]
That makes sense -- I'm going to merge this, then give it a try and see how it feels.

**Comment by tilden** [comment]
Seems good to me -- I just released a new build on the Pebble store with this pattern! Thanks!

**Pull request merged**
