### PR TITLE
Correction for #65 Part 2

### PR DESCRIPTION
**Pull request by plarus**
Correction for #65 Part 2

### CODE REVIEW

**Comment by tilden** [comment]
I've merged this into master, but I need to do more testing before I can release it, because I'm worried it may have interfered up the ability to load settings from the previous version. I'll need to do more tests.

**Comment by tilden** [comment]
So this doesn't actually appear to work. It seems that re-enabling the disconnect icon doesn't actually function.

**Comment by tilden** [comment]
Not sure why, though.

**Comment by plarus** [comment]
There was a small error. Correction here: #102

**Pull request merged**
